### ISSUE TITLE
同一网页两个并发请求，会出现请求错乱。

### ISSUE THREAD

**Issue by maojindao55** [jonnyshao/wefetch#1]

**Comment by finn751** [comment]
你好，有伪代码或具体错误信息吗

**Comment by maojindao55** [comment]
@jonnyshao 
1、一个网页A B 两个请求，会出现A或B会并发多个，而且请求参数错乱异常。
2、测试 单独留 A 或 B 请求正常。

```
//index.js
  onLoad: function () {
    this.code2Check();// A请求
    this.getExamList();//B 请求
}
....
  getExamList: function() {
    var that = this;
    http.init().get('/exam/list', {
      uid: 0
    }, {header : { 'content-type': 'application/x-www-form-urlencoded' }}).then(
      res => {
        that.setData({
          papers: res.data.data.papers
        });
      });
  },
```
```
//http.js
const wf = require('./wefetch.min.js');
const config = require('../config.js');
const util = require('./util.js');
const init = (sign = true) => {
  var trace = new Date().getTime();
  wf.defaults.baseUrl = config.host;
  wf.before.use(function (request) { 
    request['data']['ts'] = Math.round(new Date().getTime() / 1000).toString(); 
    if(sign) {
       request['data']['sign'] = util.genSign(request.data); 
    } 
    console.log(trace, request);
    return request;
  });
  // interceptor response
  wf.after.use(function (response) {
    // do something ...
    console.log(trace, response);
    if(response.statusCode !== 200) {
      wx.showToast({
        title: '服务器开小差了～(' + response.statusCode + ')' ,
        icon: 'none',
        duration: 2000
      });
    }
    return response;
  })
  return wf;
};
```

**Comment by finn751** [comment]
拦截器只是处理当前的请求 响应的拦截不会返回当前的实例，这种场景下个版本会通过wf(config)来实现

**Comment by maojindao55** [comment]
@jonnyshao 我这种统一收敛请求的场景有什么，建议的hack办法没，或者下个版本release 排期是？

**Comment by finn751** [comment]
拦截器可以统一处理当前所有的请求和响应，例如加入token、数据处理等。.如果是同一个项目有两个或两个以上不同的请求api路径，需要通过创建实例来区分，现版本还未对其适配。现在人在老家，用手机联的网，下次release预计年初6。
另外，报错信息最好能提供一下，建议尝试直接使用wf.get()。

**Comment by finn751** [comment]
> @maojindao55 
> 1、一个网页A B 两个请求，会出现A或B会并发多个，而且请求参数错乱异常。
> 2、测试 单独留 A 或 B 请求正常。
> 
> ```
> //index.js
>   onLoad: function () {
>     this.code2Check();// A请求
>     this.getExamList();//B 请求
> }
> ....
>   getExamList: function() {
>     var that = this;
>     http.init().get('/exam/list', {
>       uid: 0
>     }, {header : { 'content-type': 'application/x-www-form-urlencoded' }}).then(
>       res => {
>         that.setData({
>           papers: res.data.data.papers
>         });
>       });
>   },
> ```
> ```
> //http.js
> const wf = require('./wefetch.min.js');
> const config = require('../config.js');
> const util = require('./util.js');
> const init = (sign = true) => {
>   var trace = new Date().getTime();
>   wf.defaults.baseUrl = config.host;
>   wf.before.use(function (request) { 
>     request['data']['ts'] = Math.round(new Date().getTime() / 1000).toString(); 
>     if(sign) {
>        request['data']['sign'] = util.genSign(request.data); 
>     } 
>     console.log(trace, request);
>     return request;
>   });
>   // interceptor response
>   wf.after.use(function (response) {
>     // do something ...
>     console.log(trace, response);
>     if(response.statusCode !== 200) {
>       wx.showToast({
>         title: '服务器开小差了～(' + response.statusCode + ')' ,
>         icon: 'none',
>         duration: 2000
>       });
>     }
>     return response;
>   })
>   return wf;
> };
我们测试了这个代码片段的并发请求，一切正常，未能复现参数错乱这个问题，请提供一下具体的错误信息

**Comment by maojindao55** [comment]
@jonnyshao 辛苦了。
并没有报错信息，只是请求有些混乱。
```
  wf.before.use(function (request) { 
    console.log(trace, request);
    request['data']['ts'] = Math.round(new Date().getTime() / 1000).toString(); 
    if(sign) {
       request['data']['sign'] = util.genSign(request.data); 
    } 
    return request;
  });
```
请求A， 这个console.log(trace, request) 走了两次，说明 wf.before.use(）执行了两次，导致我注入的签名混乱，接口返回签名错误。
![image](https://user-images.githubusercontent.com/6436125/52166059-8047ec00-2743-11e9-86e2-a92a0acc2c7f.png)

**Comment by finn751** [comment]
@maojindao55  
 init函数包装后，JS会产生闭包，return wf后，上一次的wf对象并没有被销毁，建议这样处理
````
const wf = require('wefetch')

wf.defaults.baseUrl = config.host;
wf.before.use(function (request) { 
var trace = new Date().getTime();
  request['data']['ts'] = Math.round(new Date().getTime() / 1000).toString(); 
  if(sign) {
     request['data']['sign'] = util.genSign(request.data);
  } 
//   console.log(trace, request);
  return request;
});
// interceptor response
wf.after.use(function (response) {
  // do something ...
//   console.log(trace, response);
  if(response.statusCode !== 200) {
    wx.showToast({
      title: '服务器开小差了～(' + response.statusCode + ')' ,
      icon: 'none',
      duration: 2000
    });
  }
//   console.log('after')
  return response;
})

export const getExamList = (params, config) => wf.get('/exam/list', params, config)

// 使用
 getExamList({uid: 0},{header:{}}).then(res=>{
    // do something
  })
````

**Comment by maojindao55** [comment]
@jonnyshao 感谢 ，我试试，不过很奇怪一点A B 两个请求， 只有A 请求有两次wf.before.use， B请求一切正常。如果wf未销毁，理论上B请求不会出现才对。

**Comment by finn751** [comment]
@maojindao55 
新年快乐！！ 猪年大吉！！

 拦截器在项目中只需注册一次，init函数每执行一次就会注册一次。拦截器的管理目前是通过数组处理的，再加上JS闭包特性会导致这个问题。实际上应该是B执行两次才对
