### ISSUE TITLE
微信小程序引入后导致的问题

### ISSUE THREAD

**Issue by SongChao1123** [jonnyshao/wefetch#10]
const wf = require('./wf.js');
然后使用 const wxfetch = require('../config/request.js')  后，小程序会报 
VM3628:1 [non-writable] modification of global variable "Promise.prototype.finally" is not allowed when using plugins at app.json.

查询后好像是说我的项目中使用了第三方插件；我现在需要全局重写App，Page；直接报下面的错误了

**Comment by finn751** [comment]
从报错来看，现在的微信小程序已经支持`finally `这个方法
晚上我发布一版

**Comment by SongChao1123** [comment]
o(￣▽￣)ｄ

**Comment by finn751** [comment]
已发版，请下载最新版
另外我这边用之前的版本测试并未发现这个问题，你的小程序基础库版本多少?

**Comment by SongChao1123** [comment]
基础库版本是 2.10.3 的
