### ISSUE TITLE
更新版本之后1.2.5，wefetch.post和postJSON在钉钉上都发送get请求

### ISSUE THREAD

**Issue by Akimotorakiyu** [jonnyshao/wefetch#3]
更新后，wefetch在钉钉上post和postJSON均发送get请求，而不是post请求。

吓的我赶紧把版本锁定到1.2.4

**Comment by finn751** [comment]
已修复发布...
1.2.5版本后 参数配置比之前更友好
before
```js
wf.get(url,{content: 'xxx'},{eventType: 'user',header:{}})
```
now

```js
wf.get(url,{data:{},config:{eventType: 'user'},header:{}})
```

**Comment by Akimotorakiyu** [comment]
@jonnyshao post和postJSON的区别是什么？
在钉钉里：
我用postJSON也不能正常的发json数据鸭，而且postJson和post的数据格式都是`application/x-www-form-urlencoded`

**Comment by finn751** [comment]
默认所有的请求 
```
 Content-Type : application/x-www-form-urlencoded
```
postJson 

```
Content-Type : application/json
```
清除一下缓存试试

**Comment by Akimotorakiyu** [comment]
我所有的post请求都用的是`postJson`，但是都是` Content-Type : application/x-www-form-urlencoded`
![图片](https://user-images.githubusercontent.com/31165554/58064043-40522b00-7bb3-11e9-9ecf-b5426dcbb127.png)

**Comment by finn751** [comment]
现在可以了，因为阿里系的小程序设置请求头是用的header复数形式

如果全部是json 格式,建议写在拦截器里
