### ISSUE TITLE
钉钉小程序里header无法设置Authorization头

### ISSUE THREAD

**Issue by Akimotorakiyu** [jonnyshao/wefetch#4]
钉钉里面：

## 拦截器，在上面加了Authorization头
![图片](https://user-images.githubusercontent.com/31165554/58017519-06d9db00-7b33-11e9-8110-717711592cc1.png)
## 然后请求里面没有
![图片](https://user-images.githubusercontent.com/31165554/58017602-312b9880-7b33-11e9-8e08-399d2a4ec8b8.png)

## 如果是用原生的，就能加上去。
![图片](https://user-images.githubusercontent.com/31165554/58017708-76e86100-7b33-11e9-97a2-324932a0eb67.png)

**Comment by finn751** [comment]
<img width="1004" alt="author" src="https://user-images.githubusercontent.com/18613989/58019213-95505b80-7b37-11e9-98d5-ff1da9acef4c.png">
在微信小程序测试下来是可以的，你看一下写法，钉钉我回头测试一下

**Comment by finn751** [comment]
@SilverLeaves 已修复发布，这是支付小程序api不统一导致的，现已特殊处理
[my.request](https://docs.alipay.com/mini/api/owycmh)

**Comment by Akimotorakiyu** [comment]
阿里小程序有两个发送Http请求的函数，my.request这个在钉钉上支持情况未知！？看下图
![图片](https://user-images.githubusercontent.com/31165554/58063853-85299200-7bb2-11e9-98b2-8ef73aa69242.png)

> 支付宝端旧接口 my.httpRequest 将被废弃，请使用my.request 来代替。钉钉端目前尚未支持my.request，请继续使用 my.httpRequest。

**Comment by finn751** [comment]
钉钉现在支持的是my.httpRequest 后续可能会改成my.request 
已经做了适配，会自动切换当前支持的api

**Comment by Akimotorakiyu** [comment]
升级1.2.7后我这里出现了未知的棘手问题（模拟器里一切OK，但是真机部分请求失败，错误描述莫名其妙），我需要先维持在1.2.4把作业交了，然后才能回来继续看发生了什么问题。

**Comment by finn751** [comment]
能截个图出来吗，我来看下

**Comment by Akimotorakiyu** [comment]
在1.2.4`postJson`的headers设置为json格式后，也出现了这样子的错误。prismjs是markdown里面的一个js。但是在出错的这里根本就没引用到。
差不多就是这样子的。不知道问题出在哪。

![图片](https://user-images.githubusercontent.com/31165554/58097619-6a830780-7c0a-11e9-80a2-5b3c647f6ce4.png)

**Comment by finn751** [comment]
现在是没有拿到响应还是响应内容就是这个样子？
如果响应是这样子，跟后台确认下Content-Type 、method以及后台是否有做中间件请求拦截，响应了一个错误页面
你这个是钉钉吗，钉钉我记得json格式需要JSON.stringify()一下

**Comment by Akimotorakiyu** [comment]
响应内容就是这样子的。
我就是后端。
这是后端直接返回的错误信息。
明天我debug一下看看。

**Comment by jonnyshao** [comment]
后台的事情，暂时就爱莫能助了...

**Comment by Akimotorakiyu** [comment]
在1.2.4postJson的headers设置为json格式后，真机测试会出现下图问题，直接被框架拦截了
![图片](https://user-images.githubusercontent.com/31165554/58150108-30604700-7c98-11e9-8bc8-c0dd1f43124e.png)

**Comment by finn751** [comment]
建议更新到最新的试一下
钉钉要转化一下的
https://open-doc.dingtalk.com/microapp/dev/httprequest

**Comment by Akimotorakiyu** [comment]
看到了，蟹蟹。我会尽快升级的。我需要先处理后端，后端需要做一个中间件：当为`application/json`时候，若body为`string`，则`parser`一下。
PS: 因为个人习惯axios模式的，一般我所有的请求的body都是走`application/json`。很少用`application/x-www-form-urlencoded`。

**Comment by Akimotorakiyu** [comment]
@jonnyshao 有关这个和 https://github.com/jonnyshao/wefetch/issues/3 bug的issue，你可以暂时先关了，后面发现了问题再开。

**Comment by finn751** [comment]
设计当初主要是考虑兼容性， 钉钉默认是`application/x-www-form-urlencoded`其它是小程序JSON格式，我回头改成小程序默认的，不做任何的处理

**Comment by Akimotorakiyu** [comment]
@jonnyshao JSON是我的最爱。问题解决了，不需要做中间件，发送数据时候，只要`json`数据parser成string就好了。

## 嗯，我会加一个全局拦截器，全部拦截成`application/json`
