### ISSUE TITLE
参照微信,对钉钉和支付宝 content-type 默认设置为 application/json，并对data进行stringify

### ISSUE THREAD

**Issue by Akimotorakiyu** [jonnyshao/wefetch#5]
参照微信https://developers.weixin.qq.com/miniprogram/dev/api/wx.request.html
![图片](https://user-images.githubusercontent.com/31165554/58155012-9ef7d180-7ca5-11e9-8bc5-a50e6888e4eb.png)

* 钉钉和支付宝 `content-type` 默认设置为 `application/json`
* 并且`content-type`为 `application/json` 时对`data`进行`parser`

**Comment by finn751** [comment]
下个发行会考虑加入，可以在拦截器里设置
```
wf.before.use(req => {
  if(req.data){
    req.data = JSON.stringify(req.data)
  }
// do something...
  return req
})
```

**Comment by Akimotorakiyu** [comment]
![图片](https://user-images.githubusercontent.com/31165554/58157366-bb4a3d00-7caa-11e9-8ed5-dc1e7bb43bcb.png)

**Comment by jonnyshao** [comment]
原因找到了，钉钉现在的用的是旧的my.httpRequest，这个api没有做序列化工作,新的my.request跟微信的api是一样的。
我来处理下序列化吧
[钉钉文档](https://open-doc.dingtalk.com/microapp/dev/httprequest)
[支付宝文档](https://docs.alipay.com/mini/api/network)

**Comment by finn751** [comment]
https://github.com/ljharb/qs
可以使用这个库对数据进行`queryStirng` 和 `serialize`,支持deep数据结构，目前好像只有钉钉有这个问题，就不集成到`wefetch`了
