### ISSUE TITLE
typescript支持，添加type声明

### ISSUE THREAD

**Issue by Akimotorakiyu** [jonnyshao/wefetch#6]
typescript支持，添加type声明

**Comment by finn751** [comment]
2.0在准备了，会采用TS+ES6,不过到节前应该没什么时间，欢迎PR

**Comment by SilverLeaves** [comment]
正在写了。。。

**Comment by Akimotorakiyu** [comment]
@jonnyshao 直接PR到master分支？
#7

**Comment by finn751** [comment]
已merge，我未做测试，可以帮忙测试一下，这段时间实在太忙...

**Comment by Akimotorakiyu** [comment]
简单使用：
![图片](https://user-images.githubusercontent.com/31165554/58618810-1bb62b80-82f6-11e9-8518-20f437bd9699.png)

函数重载使用
![图片](https://user-images.githubusercontent.com/31165554/58618885-38eafa00-82f6-11e9-91c1-f3112c08ad10.png)
![图片](https://user-images.githubusercontent.com/31165554/58618937-50c27e00-82f6-11e9-8d5c-bf8240e374c9.png)

**Comment by Akimotorakiyu** [comment]
@jonnyshao 想了想，`.d.ts`声明文件怎么做测试？

**Comment by finn751** [comment]
我也没有什么好方法，可以看下 JEST
https://github.com/facebook/jest
