### ISSUE TITLE
[???] 请求中参数中混入了莫名其妙的 & 

### ISSUE THREAD

**Issue by Akimotorakiyu** [jonnyshao/wefetch#8]
平台钉钉
debugger显示的数据：
![图片](https://user-images.githubusercontent.com/31165554/59401867-c9cdd500-8dce-11e9-8c4a-bb6a997008ea.png)
发出去的请求：
![图片](https://user-images.githubusercontent.com/31165554/59401932-0bf71680-8dcf-11e9-8d39-9ec1f452fd24.png)

**Comment by finn751** [comment]
你的请求url后面的`?`去掉
钉钉小程序目前使用的旧的`my.httpRequest`,有比较多的历史遗留问题

**Comment by Akimotorakiyu** [comment]
抱歉，这是我的失误。
